export const QUEUED_CHATS = "queuedChats";
export const CHAT_IN_PROGRESS = "progressChats";
export const CHAT_HISTORY = "historyChats";
// Rocket Chat API Endpoints
export const LOGIN_API = "/api/v1/login";
export const LIVECHAT_QUEUED_CHATS_API = "/api/v1/livechat/inquiries.queued";
export const LIVECHAT_ROOMS_API = "/api/v1/livechat/rooms";
export const LIVECHAT_MESSAGES_API = "/api/v1/livechat/messages.history/";
export const AGENT_INFO = "/api/v1/livechat/users/agent/";
